### ISSUE TITLE
Permission denied in /run

### ISSUE THREAD

**Issue by pszafer** [Aterfax/pbs-client-docker#6]
Hi,

I tried on 3 different Linux systems your image and always end up with:
```
pbs-client  | /package/admin/s6-overlay-3.1.6.2/libexec/stage0: 87: exec: /run/s6/basedir/bin/init: Permission denied
```

All are Arch based distro.
Can you help with that?
Thanks!

**Comment by Aterfax** [comment]
Not without more info.

Please format your issue so that I know:

1.  Which image you are running including the version tag?
2.  Where this error comes from, the container log?
3.  What container runtime you are using? Podman? Docker? 
4. How you are running the container? A compose? A command?
5. What version OS as well as the distro name?

Finger in the air, I'd guess your host OS is causing some kind of problem with the way it is attempting to run the container as I haven't had any warnings about backups failing to complete.

**Comment by pszafer** [comment]
hi, thanks for response.
ad 1. tag, latest from `2024-11-23`
ad 2. Container logs
ad 3. Docker
ad 4. Docker-compose
ad 5. tried on Arch Linux / Endeavour OS, Alpine Linux, Synology NAS with docker-compose. All with same error.

I'm just cloning your repository and run `docker-compose up` in docker-compose directory.

**Comment by Aterfax** [comment]
Replicated in Endeavour OS.

**Comment by Aterfax** [comment]
Please try using

```
    tmpfs:
      - /tmp:exec
      - /run:exec
```

This appears to work on my test system.

**Comment by pszafer** [comment]
Thanks!
