### ISSUE TITLE
Spawn: Function not implemented

### ISSUE THREAD

**Issue by pszafer** [Aterfax/pbs-client-docker#8]
Hi,

This is error I got on Synology NAS in docker logs:
```
[custom-init] No custom files found, skipping...
[key_setup] 2024-11-28 20:54:01 Client encryption keyfile does not exist. Creating new client encryption keyfile.
[key_setup] 2024-11-28 20:54:02 spawn proxmox-backup-client key create
send: spawn id exp3 not open
    while executing
"send "$random_password\r""
    (file "/etc/s6-overlay/s6-rc.d/key_setup/client_key" line 5)
[key_setup] 2024-11-28 20:54:02 creating default key at: "/root/.config/proxmox-backup/encryption-key.json"
s6-rc: warning: unable to start service key_setup: command exited 1
[key_setup] 2024-11-28 20:54:02 Error: Function not implemented (os error 38)
[key_setup] 2024-11-28 20:54:02 Error occurred (Exit code: 1)
```

I can do the initialization part on another system, so it's not big deal, but just thought that's its worth you know about that.

**Comment by Aterfax** [comment]
Interesting. It suggests that something in `proxmox-backup-client` is likely making an unsupported system call so the expect script has nothing to wait for as the process halts. 

This might be something restricted by the Synology docker setup or possibly caused by the kernel used?

It seems likely that the backup client may not work at all under Synology given this, but I cannot do any testing as I don't have one.

If you run the container interactively and call the ``proxmox-backup-client`` command or ``proxmox-backup-client key create`` command what happens?

Please also try setting

```
    privileged: true
```

Cheers!

**Comment by pszafer** [comment]
With privileged or without it prints:
```
root@pbs-client:/# proxmox-backup-client key create
creating default key at: "/root/.config/proxmox-backup/encryption-key.json"
Error: Function not implemented (os error 38)
```

I see I'm not the only one https://forum.proxmox.com/threads/backup-client-encryption-not-working-inside-docker-container.139054/

**Comment by Aterfax** [comment]
Added a new FAQ element here: https://github.com/Aterfax/pbs-client-docker?tab=readme-ov-file#error-function-not-implemented-os-error-38

Ta!
